# Generated by Django 4.0.4 on 2022-05-05 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('name_category', models.CharField(max_length=255, verbose_name='Название категории')),
                ('parent_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='password.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Название категории',
                'verbose_name_plural': 'Название категории',
                'ordering': ['-time_create', 'name_category'],
            },
        ),
        migrations.CreateModel(
            name='IndexContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='password_store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, verbose_name='Логин')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
                ('description', models.TextField(blank=True)),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('time_update', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='get_category', to='password.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Данные для автоизации',
                'verbose_name_plural': 'Данные для автоизации',
                'ordering': ['-time_create'],
            },
        ),
    ]
