# Generated by Django 4.0.4 on 2022-05-05 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='password.category', verbose_name='Категория'),
        ),
    ]
