# Generated by Django 4.0.4 on 2022-06-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0002_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.TextField(default='0247f81e-8ed9-4148-a4cf-c83ab21392d8', editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
