# Generated by Django 4.0.4 on 2022-06-04 21:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0004_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.TextField(default=uuid.UUID('9795c2a7-5657-4ca1-8ebf-360660060dbb'), primary_key=True, serialize=False, unique=True),
        ),
    ]
