# Generated by Django 4.0.4 on 2022-05-13 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0006_alter_category_parent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='password_store',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='get_category', to='password.category', verbose_name='Категория'),
        ),
    ]
