# Generated by Django 4.0.4 on 2022-06-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0006_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
