# Generated by Django 4.0.4 on 2022-05-13 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('password', '0007_alter_password_store_parent_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='password_store',
            new_name='PasswordStore',
        ),
    ]
