# Generated by Django 4.0.4 on 2022-05-25 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('password', '0008_rename_password_store_passwordstore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordstore',
            options={'ordering': ['-time_create'], 'verbose_name': 'Элементы авторизации', 'verbose_name_plural': 'Элементы авторизации'},
        ),
        migrations.AddField(
            model_name='category',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='passwordstore',
            name='user_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='passwordstore',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
