# Generated by Django 4.0.4 on 2022-06-04 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('parent_id', models.TextField(blank=True, default=None, null=True, verbose_name='Категория')),
                ('name_category', models.CharField(max_length=255, verbose_name='Название категории')),
                ('create_utc', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
            ],
            options={
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PasswordStores',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('login', models.TextField(verbose_name='Логин')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('create_utc', models.TextField(blank=True, verbose_name='Время создания')),
                ('parent_id', models.TextField(verbose_name='Категория')),
            ],
            options={
                'db_table': 'password_store',
            },
        ),
    ]
