# Generated by Django 4.0.5 on 2022-06-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_db', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.RenameField(
            model_name='passwordstore',
            old_name='parent_id',
            new_name='parent',
        ),
        migrations.AlterModelTable(
            name='categories',
            table='categories',
        ),
        migrations.AlterModelTable(
            name='passwordstore',
            table='password_store',
        ),
    ]
